📝 (angular_deploy.yml): improve build and deployment workflow by adding more detailed output information for debugging purposes

diff --git a/.github/workflows/angular_deploy.yml b/.github/workflows/angular_deploy.yml
--- a/.github/workflows/angular_deploy.yml
+++ b/.github/workflows/angular_deploy.yml
@@ -28,9 +28,14 @@ jobs:
         run: npm run build:prod
 
       - name: Verify Build Output
-        run: ls -la ./dist/todo-app/browser
+        run: |
+          echo "Listing dist directory:"
+          ls -la dist
+          echo "Listing todo-app/browser directory:"
+          ls -la dist/todo-app/browser || echo "Folder not found!"
 
       - name: Upload Artifact
+        if: success()
         uses: actions/upload-artifact@v3
         with:
           name: angular-build
@@ -54,10 +59,10 @@ jobs:
         uses: actions/download-artifact@v3
         with:
           name: angular-build
-          path: dist
+          path: dist/todo-app/browser
 
       - name: Verify Downloaded Files
-        run: ls -la dist
+        run: ls -la dist/todo-app/browser || echo "Downloaded folder not found!"
 
       - name: Deploy to GitHub Pages
         id: deployment
